[project]
name = "hamilton-protocols"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["adaptyv-lab"]

[tool.uv.sources]
adaptyv-lab = { git = "https://github.com/adaptyvbio/adaptyv-lab.git" }
